name: Build, Tag & Deploy Frontend to S3

on:
  push:
    branches: ["test-s3"]

permissions:
  contents: write

env:
  AWS_REGION: eu-north-1
  S3_BUCKET: ${{ secrets.FRONTEND_S3_BUCKET }}

jobs:
  build-and-deploy:
    name: Build, Tag and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build -- --configuration=production

      - name: Create release tag
        id: create_tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          TAG="v$(date +%Y%m%d%H%M%S)-${GITHUB_SHA::7}"

          echo "TAG=$TAG" >> "$GITHUB_ENV"
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"

          git tag -a "$TAG" -m "CI: release $TAG"
          git push origin "refs/tags/$TAG"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Angular files to S3
        run: |
          aws s3 sync dist/amcart/browser/ s3://$S3_BUCKET/ \
            --delete \
            --exclude "config.json"

      - name: Set index.html cache policy
        run: |
          aws s3 cp s3://$S3_BUCKET/index.html \
            s3://$S3_BUCKET/index.html \
            --metadata-directive REPLACE \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html"
      # Invalidate only index.html
      - name: Invalidate CloudFront index.html
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/index.html"


      - name: Deployment summary
        run: |
          echo "Frontend deployed successfully"
          echo "Release: ${{ steps.create_tag.outputs.TAG }}"
          echo "S3 Bucket: $S3_BUCKET"
